# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=6)),
                ('name', models.TextField()),
                ('slot', models.CharField(max_length=20)),
                ('oldNo', models.CharField(max_length=20)),
                ('groupText', models.CharField(max_length=20)),
                ('safetyAmount', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('buyAmount', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('itemType', models.BooleanField()),
                ('BUn', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('totalPrice', models.IntegerField()),
                ('Pe', models.IntegerField()),
                ('Plnt', models.IntegerField()),
                ('Sloc', models.IntegerField()),
                ('itemGroup', models.IntegerField()),
                ('itemUsage', models.TextField()),
                ('updateDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('realAmount', models.IntegerField()),
                ('updateDate', models.DateField(auto_now=True)),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.item')),
            ],
        ),
    ]
