# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discription',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Pe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Plnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sloc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='buyAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemUsage',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='safetyAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='totalAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcheck',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcheck',
            name='realAmount',
            field=models.IntegerField(default='none'),
        ),
    ]
