# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20170423_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='item',
            name='Pe',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='Plnt',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='Sloc',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='buyAmount',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='safetyAmount',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='totalAmount',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='updateDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
